vectorfield:
  _target_: rfm_docking.architectures.DockCSPNet
  hidden_dim: 128
  time_dim: 64
  num_layers: 3
  act_fn: silu
  dis_emb: sin
  num_freqs: 32

  ln: true
  use_log_map: true  # false would put it in line with DiffCSP (euclidean distance function)
  self_edges: false
  self_cond: ${model.self_cond}
  drop_be_prob: 1.0

  zeolite_edges:
    edge_style: knn
    max_neighbors: 8
    cutoff: 2.5
  osda_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.
  cross_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.

conjugate_model:
  _target_: rfm_docking.architectures.DockProjectedConjugatedCSPNet

module:
  _target_: rfm_docking.model_pl.DockingRFMLitModule