module:
  _target_: rfm_docking.dual_dock.model_pl.DualDockingRFMLitModule

com_dock_vectorfield:
  _target_: rfm_docking.dual_dock.architectures.DockCSPNet
  hidden_dim: 64
  time_dim: 64
  num_layers: 3
  act_fn: silu
  dis_emb: sin
  num_freqs: 32

  ln: true
  self_edges: true  # otherwise we'll get problems with loading=1 (no edges at all!) 
  self_cond: ${model.self_cond}

  osda_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 50.
  cross_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.

com_dock_model:
  _target_: rfm_docking.dual_dock.architectures.DockProjectedConjugatedCSPNet


osda_dock_vectorfield:
  _target_: rfm_docking.architectures.DockCSPNet
  hidden_dim: 64
  time_dim: 64
  num_layers: 3
  act_fn: silu
  dis_emb: sin
  num_freqs: 32

  ln: true
  self_edges: false
  self_cond: ${model.self_cond}

  osda_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.
  cross_edges:
    edge_style: knn
    max_neighbors: 10
    cutoff: 15.

osda_dock_model:
  _target_: rfm_docking.architectures.DockProjectedConjugatedCSPNet
