module:
  _target_: rfm_docking.model_pl.DockingRFMLitModule

vectorfield:
  _target_: rfm_docking.architectures.OptimizeCSPNet
  hidden_dim: 128
  time_dim: 64
  num_layers: 6
  act_fn: silu
  dis_emb: sin
  num_freqs: 64

  ln: true
  self_edges: false
  self_cond: ${model.self_cond}
  drop_be_prob: 1.0

  ### osda edges will not be used! just for compatibility
  osda_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.
  ### PUT YOUR SETTINGS HERE
  cross_edges:
    edge_style: knn
    max_neighbors: 8
    cutoff: 15.

conjugate_model:
  _target_: rfm_docking.architectures.DockProjectedConjugatedCSPNet
