module:
  _target_: rfm_docking.se3_dock.model_pl.SE3DockingRFMLitModule

vectorfield:
  _target_: rfm_docking.se3_dock.architectures.SE3DockCSPNet
  hidden_dim: 256
  time_dim: 64
  num_layers: 3
  act_fn: silu
  dis_emb: sin
  num_freqs: 64

  ln: true
  self_edges: false
  self_cond: ${model.self_cond}
  drop_be_prob: 1.0

  osda_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.
  cross_edges:
    edge_style: knn
    max_neighbors: 20
    cutoff: 15.

conjugate_model:
  _target_: rfm_docking.se3_dock.architectures.SE3DockProjectedConjugatedCSPNet
